service: dev-inzint

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  createEmployee:
    handler: main.createEmployee
    events:
      - http:
          path: /register
          method: post
  loginEmployee:
    handler: main.loginEmployee
    events:
      - http:
          path: /login
          method: post
  sentMailafterSubmit:
    handler: main.sentMailafterSubmit
    events:
      - http:
          path: /sendMail
          method: post
